adminUser:
  password: local:jx-v3/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jean-michel.oliva@fr.ibm.com
  token: local:jx-v3/pipelineUser:token
  username: jmoliva
prow:
  hmacToken: local:jx-v3/prow:hmacToken
